REM "D:\Microsoft Visual Studio\VC\Auxiliary\Build\vcvars32.bat" 
SET CommandPromptType=Native
SET DevEnvDir=D:\Microsoft Visual Studio\Common7\IDE\
SET ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
SET Framework40Version=v4.0
SET FrameworkDir=C:\Windows\Microsoft.NET\Framework\
SET FrameworkDir32=C:\Windows\Microsoft.NET\Framework\
SET FrameworkVersion=v4.0.30319
SET FrameworkVersion32=v4.0.30319
SET INCLUDE=D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\ATLMFC\include;D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
SET LIB=D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x86;D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\lib\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
SET LIBPATH=D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x86;D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\lib\x86;D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0;C:\Windows\Microsoft.NET\Framework\v4.0.30319
SET Path=D:\Microsoft Visual Studio\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86;D:\Microsoft Visual Studio\Common7\IDE\VC\VCPackages;D:\Microsoft Visual Studio\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Microsoft Visual Studio\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;D:\Microsoft Visual Studio\MSBuild\Current\bin\Roslyn;D:\Microsoft Visual Studio\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;D:\Microsoft Visual Studio\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;D:\Microsoft Visual Studio\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;D:\Microsoft Visual Studio\Common7\IDE\;D:\Microsoft Visual Studio\Common7\Tools\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Calpok\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Calpok\AppData\Local\Programs\Python\Python38\;C:\Users\Calpok\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Calpok\AppData\Local\Programs\Python\Python39\;C:\Users\Calpok\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Java\jdk-15_windows-x64_bin\jdk-15\bin;C:\cygwin64\bin;;D:\Microsoft Visual Studio\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;D:\Microsoft Visual Studio\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
SET Platform=x86
SET UCRTVersion=10.0.19041.0
SET UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
SET VCIDEInstallDir=D:\Microsoft Visual Studio\Common7\IDE\VC\
SET VCINSTALLDIR=D:\Microsoft Visual Studio\VC\
SET VCToolsInstallDir=D:\Microsoft Visual Studio\VC\Tools\MSVC\14.28.29910\
SET VCToolsRedistDir=D:\Microsoft Visual Studio\VC\Redist\MSVC\14.28.29910\
SET VCToolsVersion=14.28.29910
SET VisualStudioVersion=16.0
SET VS160COMNTOOLS=D:\Microsoft Visual Studio\Common7\Tools\
SET VSCMD_ARG_app_plat=Desktop
SET VSCMD_ARG_HOST_ARCH=x86
SET VSCMD_ARG_TGT_ARCH=x86
SET VSCMD_VER=16.9.3
SET VSINSTALLDIR=D:\Microsoft Visual Studio\
SET WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0
SET WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
SET WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
SET WindowsSDKLibVersion=10.0.19041.0\
SET WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
SET WindowsSDKVersion=10.0.19041.0\
SET __devinit_path=D:\Microsoft Visual Studio\Common7\Tools\devinit\devinit.exe
SET __DOTNET_ADD_32BIT=1
SET __DOTNET_PREFERRED_BITNESS=32
SET __VSCMD_PREINIT_PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Calpok\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Calpok\AppData\Local\Programs\Python\Python38\;C:\Users\Calpok\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Calpok\AppData\Local\Programs\Python\Python39\;C:\Users\Calpok\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Java\jdk-15_windows-x64_bin\jdk-15\bin;C:\cygwin64\bin;
SET __VSCMD_script_err_count=0